import { drizzle } from "drizzle-orm/postgres-js";
import postgres from "postgres";
import { env } from "@/env";
import {
	comboMoves,
	comboMovesRelations,
	combos,
	combosRelations,
	comboTranslations,
	comboTranslationsRelations,
	moveNotes,
	moveNotesRelations,
	moves,
	movesRelations,
	moveTransitionReferences,
	moveTransitionReferencesRelations,
	moveTranslations,
	moveTranslationsRelations,
	profiles,
	steps,
	stepsRelations,
	stepTranslations,
	stepTranslationsRelations,
	userComboFavorites,
	userComboFavoritesRelations,
	userMoveStatuses,
	userMoveStatusesRelations,
} from "./schema";

const client = postgres(env.POSTGRES_URL, {
	prepare: false,
});
export const db = drizzle({
	client,
	schema: {
		combos,
		combosRelations,
		comboMoves,
		comboMovesRelations,
		comboTranslations,
		comboTranslationsRelations,
		moveTransitionReferences,
		moveTransitionReferencesRelations,
		moves,
		movesRelations,
		moveNotes,
		moveNotesRelations,
		moveTranslations,
		moveTranslationsRelations,
		profiles,
		steps,
		stepsRelations,
		stepTranslations,
		stepTranslationsRelations,
		userComboFavorites,
		userComboFavoritesRelations,
		userMoveStatuses,
		userMoveStatusesRelations,
	},
});
