export const PAGE_SIZE = 20;
export const DEBOUNCE_DELAY_MS = 250;

const SECONDS_PER_MINUTE = 60;
const MS_PER_SECOND = 1000;
const MINUTES_TO_MS = SECONDS_PER_MINUTE * MS_PER_SECOND;
const STALE_TIME_MINUTES = 5;
export const STALE_TIME_MS = STALE_TIME_MINUTES * MINUTES_TO_MS;

export const PLURAL_THRESHOLD = 5;
